org.gradle.jvmargs=-Xmx4g -Xms512m -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=false

# Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2g
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.mpp.applyDefaultHierarchyTemplate=true
kotlin.mpp.enableCInteropCommonization=true

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false
android.suppressUnsupportedCompileSdk=35

# Compose
org.jetbrains.compose.experimental.uikit.enabled=false
